version: 2

workflows:
  version: 2
  lint:
    jobs:
      - lint

  test-27:
    jobs:
      - unit-test-27
      - functional-test-27

  test-36:
    jobs:
      - unit-test-36
      - functional-test-36

jobs:
  lint:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo pip install flake8 codecov pep8-naming
      - run: sudo python setup.py install
      - run: sudo make lint

  unit-test-27:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: sudo python setup.py install
      - run: sudo make test-unit

  unit-test-36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo python setup.py install
      - run: sudo make test-unit

  functional-test-27:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          command: |
            git clone https://github.com/sstephenson/bats.git
            cd bats
            git checkout v0.4.0
            sudo ./install.sh /usr/local
            bats --version
      - run: sudo python setup.py install
      - run:
          command: |
            export TERM=xterm
            export AWS_DEFAULT_REGION=us-east-1
            export STACKER_NAMESPACE=cloudtools-functional-tests-$CIRCLE_BUILD_NUM
            export STACKER_ROLE=arn:aws:iam::459170252436:role/cloudtools-functional-tests-sta-FunctionalTestRole-1M9HFJ9VQVMFX
            sudo -E make test-functional

  functional-test-36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: |
            git clone https://github.com/sstephenson/bats.git
            cd bats
            git checkout v0.4.0
            sudo ./install.sh /usr/local
            bats --version
      - run: sudo python setup.py install
      - run:
          command: |
            export TERM=xterm
            export AWS_DEFAULT_REGION=us-east-1
            export STACKER_NAMESPACE=cloudtools-functional-tests-$CIRCLE_BUILD_NUM
            export STACKER_ROLE=arn:aws:iam::459170252436:role/cloudtools-functional-tests-sta-FunctionalTestRole-1M9HFJ9VQVMFX
            sudo -E make test-functional
